
# 日志配置
logging:
  level:
    com.wallet: debug
    org.springframework: warn

# Spring配置
spring:
  profiles: 
    active: '@package.environment@'
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置

  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.wallet.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

chain:
  data:
    eth-url: https://eth.tokenview.com/api/eth/address/normal
    eth-contract-url: https://eth.tokenview.com/api/eth/address/normal
    trx-url: https://apilist.tronscan.org/api/transfer
    trx-contract-url: https://apilist.tronscan.org/api/token_trc20/transfers
    eth-select-contract: https://ethplorer.io/service/service.php?page=1&pageSize=1000&search=
  balance:
    trx-balance: https://apiasia.tronscan.io:5566/api/account/tokens?limit=100
    eth-balance: https://ethplorer.io/service/service.php?data=
trx:
  #节点地址
  node:
    address: https://api.trongrid.io